spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://${DATASOURCE_URL}?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

aws:
  region: ${AWS_REGION}
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}

redis:
  host: 10.175.41.94
  port: 6379