server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true
  error:    path: /error
    whitelabel:      enabled: false

logging:
  config: classpath:log/logback-${spring.profiles.active}.xml